context:
  version: "2.1.0"

package:
  name: steam
  version: ${{ version }}

source:
  git: https://github.com/utiasASRL/steam.git
  rev: d7b7b550a24c2169d9df8b1b356836902ceb7886
  patches:
    - fix-march.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - eigen >=3.3.7,<4
    - lgmath
    - libboost-devel
    - yaml-cpp
  run:
    - eigen >=3.3.7,<4
    - lgmath
    - libboost-devel

tests:
  - package_contents:
      include:
        - steam.hpp
      files:
        exists:
          - lib/cmake/steam/steamConfig.cmake
          - lib/cmake/steam/steamConfigVersion.cmake

about:
  homepage: https://github.com/utiasASRL/steam
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The Simultaneous Trajectory Estimation and Mapping (STEAM) Engine.
  description: STEAM (Simultaneous Trajectory Estimation and Mapping) Engine is an optimization library aimed at solving batch nonlinear optimization problems involving both SO(3)/SE(3) and continuous-time components. This is accomplished by using an iterative Gauss-Newton-style estimator in combination with techniques developed and used by ASRL. With respect to SO(3) and SE(3) components, we make use of the constraint sensitive perturbation schemes discussed in Barfoot and Furgale [1]. STEAM Engine is by no means intended to be the fastest car on the track; the intent is simply to be fast enough for the types of problems we wish to solve, while being both readable and easy to use by people with a basic background in robotic state estimation.
  repository: https://github.com/utiasASRL/steam