context:
  version: "3.0.0"

package:
  name: lgmath
  version: ${{ version }}

source:
  git: https://github.com/utiasASRL/lgmath.git
  rev: c55431ef62d5a706f8ed0c0d81ffa8d7483e1272
  patches:
    - fix-version.patch
    - fix-march.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - eigen >=3.3.7,<4
  run:
    - eigen >=3.3.7,<4

tests:
  - package_contents:
      include:
        - lgmath.hpp
      files:
        exists:
          - lib/cmake/lgmath/lgmathConfig.cmake
          - lib/cmake/lgmath/lgmathConfigVersion.cmake

about:
  homepage: https://github.com/utiasASRL/lgmath
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Lie group math library.
  description: lgmath is a C++ library for handling geometry in state estimation problems in robotics. It is used to store, manipulate, and apply three-dimensional rotations and transformations and their associated uncertainties.
  documentation: https://github.com/utiasASRL/lgmath
  repository: https://github.com/utiasASRL/lgmath
